# Generated by Django 2.2 on 2019-05-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20190425_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.CharField(default='new field', max_length=50),
        ),
        migrations.AddField(
            model_name='owner',
            name='password',
            field=models.CharField(default='new password field', max_length=50),
        ),
    ]
