# Generated by Django 2.2 on 2019-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_auto_20190508_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='password2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
